version: 0.0
os: linux
files:
  - source:
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/delete_back_nginx
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_nginx
      timeout: 300
      runas: root